credentials:
  usernames:
    admin:
      name: admin
      password: '$2b$12$82R1SPaM7eL8wSlphPAEwudTFYgpsTpbdXte6mK9DLkY.GbUmp81m'  # yy_u2wB.nGw9afy
      role: admin
    GCC:
      name: GCC
      password: '$2b$12$lDhogRFJ7osQuH9XD9QAoONiLK3JonMLBa8XAglEEXE1du6Vd6q2e'  # PYo-8@jdGNugYJg
      role: viewer
    test:
      name: test
      password: '$2b$12$tlHS/ivZ4I44tsZO7DB.Z.hF3u8lNDJIctKhvgdGxHCHyfMVuq7UG' 

cookie:
  expiry_days: 30
  key: gcc_instagram_data_key
  name: gcc_insta_data_cookie