credentials:
  usernames:
    test:
      name: test
      password: '$2b$12$tlHS/ivZ4I44tsZO7DB.Z.hF3u8lNDJIctKhvgdGxHCHyfMVuq7UG' 

cookie:
  expiry_days: 30
  key: gcc_instagram_data_key
  name: gcc_insta_data_cookie